Working on a big cleanup of the scripts

diff --git a/.backup/scripts/_pipeline.yml b/.backup/scripts/_pipeline.yml
--- a/.backup/scripts/_pipeline.yml
+++ b/.backup/scripts/_pipeline.yml
@@ -1,218 +1,70 @@
-# Build and Deploy Jobs
-name: _InfraBuildDeploy
 
-on:
-  workflow_call:
-    inputs:
-      workspace:
-        required: true
-        type: string
-      environment:
-        required: true
-        type: string
-      infrastructure:
-        required: true
-        type: boolean
-      rebuild:
-        required: true
-        type: boolean
-      appstack:
-        required: true
-        type: string
-      services:
-        required: true
-        type: string
-    secrets:
-      BITWARDEN_TOKEN:
-        required: true
+      
 
-env:
-  APP_PATH_CONF: /etc/app
-  APP_PATH_DATA: /var/lib/data
-  APP_PATH_LOGS: /var/lib/logs
-  APP_PATH_SERV: /srv/app
-  APP_PATH_TEMP: /tmp/app
+      
+      
 
-jobs:
-  # Terraform Plan and Apply
-  # This job will run if the cache is not hit or if the initialize input is set to true
-  # Stores the output in a JSON file and uploads it as an artifact and caches it for future runs
-  terraform:
-    name: Terraform Plan and Apply
-    runs-on: ubuntu-latest
-    environment: ${{ inputs.environment }}
-    if: inputs.infrastructure == true
-    steps:
-      # Check out the repo
-      - name: Check Out
-        uses: actions/checkout@v4
-      
-      # Set up GitHub Secrets
-      - name: Get General Secrets
-        uses: bitwarden/sm-action@v2
-        id: get-secrets
-        with:
-          access_token: ${{ secrets.BITWARDEN_TOKEN }}
-          secrets: |
-            d47e736b-2db8-47d5-b46b-b2c8016ece73 > TERRAFORM_API_TOKEN
-            357068b9-9f5f-4f79-940c-b2c8016cb88f > KAMATERA_API_KEY
-            6c9295a8-9fa4-4d38-8929-b2c8016d9b43 > KAMATERA_API_SECRET
-            6cc5b975-56a9-4d7a-80c7-b2c90151cce0 > KAMATERA_PUBLIC_KEY
-            f16fffe2-77b7-4d20-bf6c-b2c9015c71d3 > KAMATERA_PRIVATE_KEY
-            5083ae32-429d-428b-b7df-b2c901441bbb > KAMATERA_ROOT_PASSWORD
-      
-      # Set up the Terraform CLI
-      - name: Set up Terraform
-        uses: hashicorp/setup-terraform@v2
-        with:
-          terraform_version: 1.5.7
-          terraform_wrapper: false
-      
-      # Run Terraform to create docker swarm cluster
-      - name: Run Terraform Apply
-        id: tfapply
-        working-directory: ./deploy/terraform
+      # Initialize the server with initialization script
+      - name: Initialize BEFORE ${{ inputs.environment }} Server ${{ matrix.label }}
         run: |
-          echo "[*] Server deployment and configuration ..."
-          export TF_TOKEN_app_terraform_io=$TERRAFORM_API_TOKEN
-          export TF_VAR_api_key=$KAMATERA_API_KEY
-          export TF_VAR_api_secret=$KAMATERA_API_SECRET
-          export TF_VAR_ssh_public_key=$KAMATERA_PUBLIC_KEY
-          export TF_VAR_password=$KAMATERA_ROOT_PASSWORD
-          export TF_VAR_workspace=${{ inputs.workspace }}
-          export TF_VAR_environment=${{ inputs.environment }}
-          export TF_LOG=DEBUG
-          export WORKSPACE=${{ inputs.workspace }}
-          export ENVIRONMENT=${{ inputs.environment }}
-          export APP_PATH_TEMP=${{ env.APP_PATH_TEMP }}
-          echo "[*] Server deployment and configuration ... APPLY"
-          chmod +x ../scripts/terraform-apply.sh
-          ../scripts/terraform-apply.sh
-          echo "[+] Server deployment and configuration ... DONE"
+          echo "[*] Copying initialization script to remote server..."
+          ssh -o StrictHostKeyChecking=no root@${{ matrix.ip }} << EOF
+            mkdir -p ${{ env.APP_PATH_TEMP }}
+            chmod 777 ${{ env.APP_PATH_TEMP }}
+          EOF
+          scp -o StrictHostKeyChecking=no \
+            "./deploy/scripts/initialize-begin.sh" \
+            "./deploy/scripts/initialize.env" \
+            "./deploy/cluster.${{ inputs.workspace }}.json" \
+            root@${{ matrix.ip }}:${{ env.APP_PATH_TEMP }}/ || {
+            echo "[x] Failed to transfer before initialization script to remote server"
+            exit 1
+          }
+          echo "[+] Copying initialization script to remote server...DONE"
+          echo "[*] Executing BEFORE initializing remotely..."
+          ssh -o StrictHostKeyChecking=no root@${{ matrix.ip }} << EOF
+            if [ -f ${{ env.APP_PATH_TEMP }}/initialize.env ]; then
+              set -a
+              source ${{ env.APP_PATH_TEMP }}/initialize.env
+              set +a
+            else
+              echo "[!] Initialization environment file not found. Exiting."
+              exit 1
+            fi
+            chmod +x ${{ env.APP_PATH_TEMP }}/initialize-begin.sh
+            ${{ env.APP_PATH_TEMP }}/initialize-begin.sh
+          EOF
+          echo "[+] Executing BEFORE initializing remotely...DONE"
 
-      # Upload the Terraform output as an artifact
-      - name: Upload Terraform Artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: terraform-output-${{ inputs.workspace }}
-          path: ${{ env.APP_PATH_TEMP }}/tf_output.json
-          if-no-files-found: error
-      
-      # Check if Terraform cache exists
-      - name: Check Existing Terraform Cache
-        id: check-cache
-        uses: actions/cache/restore@v4
-        with:
-          path: ${{ env.APP_PATH_TEMP }}/tf_output.json
-          key: terraform-output-${{ inputs.workspace }}
-
-      # Upload the Terraform output as a job output
-      - name: Cache Terraform Output
-        if: steps.check-cache.outputs.cache-hit != 'true'
-        uses: actions/cache/save@v4
-        with:
-          path: ${{ env.APP_PATH_TEMP }}/tf_output.json
-          key: terraform-output-${{ inputs.workspace }}
-
-  # Download the Terraform output artifact and parse it to find Swarm servers
-  # This job will run if the cache is not hit or if the initialize input is set to true
-  # Parses the output to find Swarm servers and sets them as a matrix for the next jobs
-  restore:
-    name: Download Terraform Output
-    runs-on: ubuntu-latest
-    needs: [terraform]
-    environment: ${{ inputs.environment }}
-    if: always()
-    outputs:
-      matrix: ${{ steps.parse.outputs.matrix }}
-    steps:
-      # Download Terraform Artifact
-      - name: Download Terraform Artifact
-        if: inputs.infrastructure == true
-        uses: actions/download-artifact@v4
-        with:
-          name: terraform-output-${{ inputs.workspace }}
-          path: ${{ env.APP_PATH_TEMP }}
-
-      # Restore Terraform Cache
-      - name: Restore Terraform Cache
-        id: restore-cache
-        if: inputs.infrastructure != true
-        uses: actions/cache/restore@v4
-        with:
-          path: ${{ env.APP_PATH_TEMP }}/tf_output.json
-          key: terraform-output-${{ inputs.workspace }}
-
-      # Check if the artifact exists
-      - name: Validate Terraform Output
+      # Initialize the server with initialization script
+      - name: Initialize ${{ inputs.environment }} Server ${{ matrix.label }}
         run: |
-          if [ ! -f ${{ env.APP_PATH_TEMP }}/tf_output.json ]; then
-            echo "[!] Artifact terraform-output-${{ inputs.workspace }} not found or tf_output.json missing. Exiting."
+          if [ -f ${{ env.APP_PATH_TEMP }}/initialize.env ]; then
+            set -a
+            source ${{ env.APP_PATH_TEMP }}/initialize.env
+            set +a
+          else
+            echo "[!] Initialization environment file not found. Exiting."
             exit 1
           fi
-
-      # Parse Terraform Output to find Swarm Servers
-      - name: Parse Swarm Servers
-        id: parse
-        run: |
-          matrix=$(jq -c '.' ${{ env.APP_PATH_TEMP }}/tf_output.json)
-          echo "================"
-          echo "$matrix"
-          echo "================"
-          echo "matrix=$matrix" >> $GITHUB_OUTPUT
-
-  # Initialize the Swarm Cluster
-  # This job will run if the cache is not hit or if the initialize input is set to true
-  # Initializes the Swarm cluster
-  initialization:
-    name: Initialize Swarm Cluster
-    needs: [restore]
-    runs-on: ubuntu-latest
-    environment: ${{ inputs.environment }}
-    if: inputs.infrastructure == true
-    strategy:
-      matrix: ${{ fromJson(needs.restore.outputs.matrix) }}
-    steps:
-      # Check out the repo
-      - name: Check Out
-        uses: actions/checkout@v4
-
-      # Set up GitHub Secrets
-      - name: Get General Secrets
-        uses: bitwarden/sm-action@v2
-        id: get-secrets
-        with:
-          access_token: ${{ secrets.BITWARDEN_TOKEN }}
-          secrets: |
-            f16fffe2-77b7-4d20-bf6c-b2c9015c71d3 > KAMATERA_PRIVATE_KEY
-
-      # Set up SSH connection
-      - name: Set up SSH connection
-        env:
-          KAMATERA_PRIVATE_KEY: ${{ steps.get-secrets.outputs.KAMATERA_PRIVATE_KEY }}
-        run: |
-          mkdir -p ~/.ssh
-          echo "$KAMATERA_PRIVATE_KEY" > ~/.ssh/id_rsa
-          chmod 600 ~/.ssh/id_rsa
-
-      # Step: Copy the key securely to the remote server using scp
-      - name: Upload Private Key
-        run: |
-          scp -o StrictHostKeyChecking=no ~/.ssh/id_rsa root@${{ matrix.ip }}:/root/.ssh/id_rsa_temp || { echo "[x] Failed to transfer private key to remote server"; exit 1; }
-
-      # Step: Initialize the Swarm cluster
-      - name: Initialize Swarm Cluster
-        env:
-          APP_PATH_CONF: ${{ env.APP_PATH_CONF }}
-          APP_PATH_DATA: ${{ env.APP_PATH_DATA }}
-          APP_PATH_LOGS: ${{ env.APP_PATH_LOGS }}
-          APP_PATH_SERV: ${{ env.APP_PATH_SERV }}
-          APP_PATH_TEMP: ${{ env.APP_PATH_TEMP }}
-          ENVIRONMENT: ${{ inputs.environment }}
-          WORKSPACE: ${{ inputs.workspace }}
-        run: |
           chmod +x deploy/scripts/initialize-swarm-server.sh
           ./deploy/scripts/initialize-swarm-server.sh "${{ matrix.ip }}" "${{ matrix.private_ip }}" "${{ matrix.manager_ip }}"
+          
+      # Initialize the server with initialization script
+      - name: Initialize AFTER ${{ inputs.environment }} Server ${{ matrix.label }}
+        run: |
+          echo "[*] Copying initialization script to remote server..."
+          scp -o StrictHostKeyChecking=no "./deploy/scripts/initialize-end.sh" root@${{ matrix.ip }}:/tmp/app/initialize-end.sh || {
+            echo "[x] Failed to transfer after initialization script to remote server"
+            exit 1
+          }
+          echo "[+] Copying initialization script to remote server...DONE"
+          echo "[*] Executing AFTER initializing remotely..."
+          ssh -o StrictHostKeyChecking=no root@${{ matrix.ip }} << 'EOF'
+            chmod +x /tmp/app/initialize-end.sh
+            /tmp/app/initialize-end.sh
+          EOF
+          echo "[+] Executing AFTER initializing remotely...DONE"
 
   # Configure the Swarm Cluster
   # This job will run if the cache is not hit or if the initialize input is set to true
@@ -230,6 +82,18 @@ jobs:
       # Check out the repo
       - name: Check Out
         uses: actions/checkout@v4
+
+      # Load environment variables from .env file
+      - name: Get Environment Variables
+        run: |
+          echo "[*] Loading variables from ./src/${{ inputs.environment }}.env file..."
+          while IFS='=' read -r key value || [ -n "$key" ]; do
+            [[ -z "$key" || "$key" == \#* ]] && continue
+            value="${value%\"}"
+            value="${value#\"}"
+            echo "$key=$value" >> "$GITHUB_ENV"
+          done < ./src/${{ inputs.environment }}.env
+          echo "[*] Loading variables from ./src/${{ inputs.environment }}.env file...DONE"
 
       # Set up GitHub Secrets
       - name: Get General Secrets
@@ -285,26 +149,40 @@ jobs:
           mkdir -p ~/.ssh
           echo "$KAMATERA_PRIVATE_KEY" > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
-      
-      # Step: Configure Server
+
+      # Configure Swarm Server
       - name: Configure Server
+        run: |
+          echo "[*] Server configuration..."
+          export APP_PATH_CONF=${{ env.APP_PATH_CONF }}
+          chmod +x deploy/scripts/configure-swarm-server.sh
+          ./deploy/scripts/configure-swarm-server.sh "${{ matrix.ip }}" "${{ inputs.environment }}"
+          echo "[+] Server configuration...DONE"
         env:
-          APP_PATH_CONF: ${{ env.APP_PATH_CONF }}
-          APP_PATH_DATA: ${{ env.APP_PATH_DATA }}
-          APP_PATH_LOGS: ${{ env.APP_PATH_LOGS }}
-          APP_PATH_SERV: ${{ env.APP_PATH_SERV }}
-          APP_PATH_TEMP: ${{ env.APP_PATH_TEMP }}
-          ENVIRONMENT: ${{ inputs.environment }}
-          WORKSPACE: ${{ inputs.workspace }}
           PLATFORM_USERNAME: ${{ steps.get-secrets.outputs.PLATFORM_USERNAME }}
           PLATFORM_PASSWORD: ${{ steps.get-secrets.outputs.PLATFORM_PASSWORD }}
           TRAEFIK_CLIENTID : ${{ steps.get-secrets.outputs.TRAEFIK_CLIENTID }}
           TRAEFIK_SECRET : ${{ steps.get-secrets.outputs.TRAEFIK_SECRET }}
           VERSIO_USERNAME : ${{ steps.get-secrets.outputs.VERSIO_USERNAME }}
           VERSIO_PASSWORD : ${{ steps.get-secrets.outputs.VERSIO_PASSWORD }}
+
+      # Configure Application Services
+      - name: Configure App Services
         run: |
-          chmod +x deploy/scripts/configure-swarm-server.sh
-          ./deploy/scripts/configure-swarm-server.sh "${{ matrix.ip }}"
+          echo "[*] Service configuration..."
+          chmod +x deploy/scripts/configure-services.sh
+          ./deploy/scripts/configure-services.sh "${{ matrix.ip }}"
+          echo "[+] Service configuration...DONE"
+
+      # Finish Configuration
+      - name: Finish Configuration
+        run: |
+          echo "[*] Finishing configuration..."
+          ssh -o StrictHostKeyChecking=no root@${{ matrix.ip }} << 'EOF'
+            chmod +x /tmp/app/configure-end.sh
+            /tmp/app/configure-end.sh
+          EOF
+          echo "[*] Finishing configuration...DONE"
 
   # Get all metadata.json files and set them as a matrix
   # This job will run if the rebuild input is set to true
