Add PostgreSQL and PGAdmin to the services (#28)
* Refactor PostgreSQL setup: remove unused scripts, add Docker secrets, and enhance initialization process

* Add pgAdmin service to Docker Compose and update environment files with APP_ROOT_EMAIL

* Add GitHub Secrets setup for different environments in pipeline

* Refactor environment files: remove VERSIO_ENDPOINT and ensure TRAEFIK_MIDDLEWARES consistency across all environments

* Update testResolver to use dns and versio

* Added versio_endpoint and test resolvers

* Removed resources

* Update PostgreSQL deployment on worker-1 node and logging: add pgAdmin to services, update worker node label, and enhance log clearing script

* Add conditional check for updating worker-1 node with postgres tag

* Add postgres-init service with configuration for database initialization

* Add PostgreSQL configuration setup in development script

* Fix indentation in worker-1 node update script for PostgreSQL tag

* Fix conditional check for updating worker-1 node with postgres tag

diff --git a/.github/workflows/_pipeline.yml b/.github/workflows/_pipeline.yml
--- a/.github/workflows/_pipeline.yml
+++ b/.github/workflows/_pipeline.yml
@@ -472,6 +472,7 @@ jobs:
           access_token: ${{ secrets.BITWARDEN_TOKEN }}
           secrets: |
             f16fffe2-77b7-4d20-bf6c-b2c9015c71d3 > KAMATERA_PRIVATE_KEY
+            5083ae32-429d-428b-b7df-b2c901441bbb > APP_ROOT_PASSWORD
 
       # Set up GitHub Secrets for Staging Environment
       - name: Get Staging Secrets
@@ -481,6 +482,7 @@ jobs:
           access_token: ${{ secrets.BITWARDEN_TOKEN }}
           secrets: |
             0c1f1f1c-456b-47d5-aad4-b2c9015ca6dc > KAMATERA_PRIVATE_KEY
+            924b9526-a6cf-43c1-93a9-b2c9014494ae > APP_ROOT_PASSWORD
 
       # Set up GitHub Secrets for Production Environment
       - name: Get Production Secrets
@@ -490,6 +492,7 @@ jobs:
           access_token: ${{ secrets.BITWARDEN_TOKEN }}
           secrets: |
             02ed2dea7-b72e-401b-ae7e-b2c9015cd76e > KAMATERA_PRIVATE_KEY
+            6db5856c-3f7f-4b62-9846-b2c90144cb0b > APP_ROOT_PASSWORD
 
       # Set up SSH connection
       - name: Set up SSH connection
@@ -506,6 +509,7 @@ jobs:
           
           echo "[*] Copying variables to remote server..."
           cat <<EOF > /tmp/secrets.env
+          APP_ROOT_PASSWORD=$APP_ROOT_PASSWORD
           VERSIO_USERNAME=$VERSIO_USERNAME
           VERSIO_PASSWORD=$VERSIO_PASSWORD
           EOF
@@ -532,6 +536,42 @@ jobs:
           # Execute the configuration script remotely
           echo "[*] Executing configuration script remotely..."
           ssh -o StrictHostKeyChecking=no root@${{ matrix.ip }} << 'EOF'
+            # Function to create a path if it does not already exist
+            createpath() {
+              local newpath="$1"
+
+              if [ ! -d "$newpath" ]; then
+                echo "[*] Creating directory: $newpath"
+                if ! mkdir -p "$newpath"; then
+                  echo "[x] Error: Failed to create directory '$newpath'"
+                  return 1
+                fi
+              fi
+
+              echo "[*] Setting permissions on $newpath"
+              sudo chmod -R 777 "$newpath"
+
+              return 0
+            }
+
+            # Create the necessary directories
+            createpath "/app"
+
+            createpath "/app/traefik"
+            createpath "/app/traefik/conf"
+            createpath "/app/traefik/data"
+            createpath "/app/traefik/logs"
+            
+            createpath "/app/consul"
+            createpath "/app/consul/conf"
+            createpath "/app/consul/data"
+
+            createpath "/app/postgres"
+            createpath "/app/postgres/conf"
+            createpath "/app/postgres/data"
+            createpath "/app/postgres/admin"
+            createpath "/app/postgres/backups"
+
             chmod +x /tmp/configure.sh
             /tmp/configure.sh
             cp /tmp/variables.env /app/.env
@@ -570,6 +610,26 @@ jobs:
           }
           echo "[*] Deploying CONSUL to remote server...DONE"
 
+      # Configure Postgres Server
+      - name: Configure Postgres
+        run: |
+          # POSTGRES
+          echo "[*] Deploying POSTGRES to remote server..."
+          scp -o StrictHostKeyChecking=no ./src/postgres/* root@${{ matrix.ip }}:/app/postgres/conf/ || {
+            echo "[x] Failed to transfer postgres configuration to remote server"
+            exit 1
+          }
+          # Update the worker-1 node with the postgres tag
+          if [[ "$hostname" != *"manager-1"* ]]; then
+            exit 0
+          fi
+          echo "[*] Updating worker-1 node with postgres tag..."
+          ssh -o StrictHostKeyChecking=no root@${{ matrix.ip }} << 'EOF'
+          POSTGRES_NODE=$(docker node ls --format '{{.Hostname}}' | grep "worker-1")
+          docker node update --label-add postgres=true $POSTGRES_NODE
+          EOF
+          echo "[*] Deploying POSTGRES to remote server...DONE"
+
       # Finish Configuration
       - name: Finish Configuration
         run: |
@@ -598,15 +658,44 @@ jobs:
     strategy:
       matrix: ${{ fromJson(needs.download.outputs.matrix) }}
     steps:
-      # Start the environment
-      - name: Start Environment
-        if: ${{ matrix.label == 'manager_1' }}
-        run: |  
-          echo "[*] Set up SSH Connection..."
+      # Set up GitHub Secrets for Test Environment
+      - name: Get Test Secrets
+        if: ${{ inputs.environment == 'test' }}
+        uses: bitwarden/sm-action@v2
+        with:  
+          access_token: ${{ secrets.BITWARDEN_TOKEN }}
+          secrets: |
+            f16fffe2-77b7-4d20-bf6c-b2c9015c71d3 > KAMATERA_PRIVATE_KEY
+
+      # Set up GitHub Secrets for Staging Environment
+      - name: Get Staging Secrets
+        if: ${{ inputs.environment == 'staging' }}
+        uses: bitwarden/sm-action@v2
+        with:  
+          access_token: ${{ secrets.BITWARDEN_TOKEN }}
+          secrets: |
+            0c1f1f1c-456b-47d5-aad4-b2c9015ca6dc > KAMATERA_PRIVATE_KEY
+
+      # Set up GitHub Secrets for Production Environment
+      - name: Get Production Secrets
+        if: ${{ inputs.environment == 'production' }}
+        uses: bitwarden/sm-action@v2
+        with:  
+          access_token: ${{ secrets.BITWARDEN_TOKEN }}
+          secrets: |
+            02ed2dea7-b72e-401b-ae7e-b2c9015cd76e > KAMATERA_PRIVATE_KEY
+
+      # Set up GitHub Secrets for Environment
+      - name: Set up SSH connection
+        run: |
           mkdir -p ~/.ssh
           echo "$KAMATERA_PRIVATE_KEY" > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
 
+      # Start the environment
+      - name: Start Environment
+        if: ${{ matrix.label == 'manager_1' }}
+        run: |
           echo "[*] Starting Environment..."
           ssh -o StrictHostKeyChecking=no root@${{ matrix.ip }} << 'EOF'
             cd /app
