Add the keycloak service (#29)
* Add Keycloak service configuration and setup scripts

* Fix Traefik middleware reference for Keycloak service and add VXLAN cleanup function in environment startup script

* Working on keycloak

* Change shebang from bash to sh in keycloak-entry.sh

* Update workflow configuration for improved job management

* Refactor permission settings in startenv.sh and update Traefik service configuration in compose.yml

* Fix Traefik resolver and update Versio API endpoint in test.env

* Clarify comments regarding app directory permissions in pipeline.yml

* Refactor directory creation and permission settings in configure.sh for improved clarity and functionality

* Restrict environment start to only the first manager node in the matrix

diff --git a/.github/workflows/_pipeline.yml b/.github/workflows/_pipeline.yml
--- a/.github/workflows/_pipeline.yml
+++ b/.github/workflows/_pipeline.yml
@@ -463,6 +463,8 @@ jobs:
           secrets: |
             f53a76ab-b87f-4af0-9aa4-b2d1016aba2b > VERSIO_USERNAME
             3d7bbfcd-18a5-4762-9064-b2d1016aef63 > VERSIO_PASSWORD
+            5db70d74-c5db-459a-b916-b2d80126d8a3 > TRAEFIK_CLIENTID
+            f5eaa406-b7cb-4ea8-b260-b2d80127303d > TRAEFIK_SECRET
 
       # Set up GitHub Secrets for Test Environment
       - name: Get Test Secrets
@@ -512,6 +514,8 @@ jobs:
           APP_ROOT_PASSWORD=$APP_ROOT_PASSWORD
           VERSIO_USERNAME=$VERSIO_USERNAME
           VERSIO_PASSWORD=$VERSIO_PASSWORD
+          TRAEFIK_CLIENTID=$TRAEFIK_CLIENTID
+          TRAEFIK_SECRET=$TRAEFIK_SECRET
           EOF
 
           # Copy secrets to remote server
@@ -521,6 +525,7 @@ jobs:
           }
 
           # Copy environment variables to remote server
+          echo "[*] Copying environment variables to remote server..."
           scp -o StrictHostKeyChecking=no ./src/${{ inputs.environment }}.env root@${{ matrix.ip }}:/tmp/variables.env || {
             echo "[x] Failed to transfer variables to remote server"
             exit 1
@@ -536,42 +541,6 @@ jobs:
           # Execute the configuration script remotely
           echo "[*] Executing configuration script remotely..."
           ssh -o StrictHostKeyChecking=no root@${{ matrix.ip }} << 'EOF'
-            # Function to create a path if it does not already exist
-            createpath() {
-              local newpath="$1"
-
-              if [ ! -d "$newpath" ]; then
-                echo "[*] Creating directory: $newpath"
-                if ! mkdir -p "$newpath"; then
-                  echo "[x] Error: Failed to create directory '$newpath'"
-                  return 1
-                fi
-              fi
-
-              echo "[*] Setting permissions on $newpath"
-              sudo chmod -R 777 "$newpath"
-
-              return 0
-            }
-
-            # Create the necessary directories
-            createpath "/app"
-
-            createpath "/app/traefik"
-            createpath "/app/traefik/conf"
-            createpath "/app/traefik/data"
-            createpath "/app/traefik/logs"
-            
-            createpath "/app/consul"
-            createpath "/app/consul/conf"
-            createpath "/app/consul/data"
-
-            createpath "/app/postgres"
-            createpath "/app/postgres/conf"
-            createpath "/app/postgres/data"
-            createpath "/app/postgres/admin"
-            createpath "/app/postgres/backups"
-
             chmod +x /tmp/configure.sh
             /tmp/configure.sh
             cp /tmp/variables.env /app/.env
@@ -630,21 +599,36 @@ jobs:
           EOF
           echo "[*] Deploying POSTGRES to remote server...DONE"
 
+      # Configure Keycloak Server
+      - name: Configure Keycloak
+        run: |
+          # KEYCLOAK
+          echo "[*] Deploying KEYCLOAK to remote server..."
+          # Generate realm.json
+          envsubst < ./src/keycloak/keycloak-realm.template.json > ./src/keycloak/keycloak-realm.json
+          # Copy the keycloak configuration to the remote server
+          scp -o StrictHostKeyChecking=no ./src/keycloak/* root@${{ matrix.ip }}:/app/keycloak/conf/ || {
+            echo "[x] Failed to transfer keycloak configuration to remote server"
+            exit 1
+          }
+          echo "[*] Deploying KEYCLOAK to remote server...DONE"
+
       # Finish Configuration
       - name: Finish Configuration
         run: |
           echo "[*] Finishing configuration..."
           ssh -o StrictHostKeyChecking=no root@${{ matrix.ip }} << 'EOF'
             # Set environment file
-            cp -f /tmp/${{ inputs.environment }}.env /app/.env
+            cp -f /tmp/variables.env /app/.env
             
-            # Set permissions for the app directory
-            chown -R 777 /app
-            chmod -R 600 /app/traefik/data
+            # Set permissions for the app directory does not have to be done here
+            # Correct permissions for the app directory are set in the startenv.sh script
+            # This would break the permissions for the app directory when its running
+            # chown -R 755 /app
 
             # Remove temporary files
-            rm -f /tmp/variables.env
-            rm -f /tmp/secrets.env
+            #rm -f /tmp/variables.env
+            #rm -f /tmp/secrets.env
           EOF
           echo "[*] Cleanup temporary files...DONE"
 
@@ -694,11 +678,15 @@ jobs:
 
       # Start the environment
       - name: Start Environment
-        if: ${{ matrix.label == 'manager_1' }}
         run: |
           echo "[*] Starting Environment..."
+          if [[ "${{ matrix.name }}" != *"manager-1"* ]]; then
+            exit 0
+          fi
+
           ssh -o StrictHostKeyChecking=no root@${{ matrix.ip }} << 'EOF'
             cd /app
+            ./stopenv.sh
             ./startenv.sh
           EOF
           echo "[*] Starting Environment...DONE"
