Updating deployment scripts

diff --git a/.github/workflows/_pipeline.yml b/.github/workflows/_pipeline.yml
--- a/.github/workflows/_pipeline.yml
+++ b/.github/workflows/_pipeline.yml
@@ -40,6 +40,7 @@ jobs:
       # Set up GitHub Secrets
       - name: Get General Secrets
         uses: bitwarden/sm-action@v2
+        id: get-secrets
         with:
           access_token: ${{ secrets.BITWARDEN_TOKEN }}
           secrets: |
@@ -60,9 +61,9 @@ jobs:
       # Run Terraform to create docker swarm cluster
       - name: Run Terraform Apply
         id: tfapply
-        working-directory: ./deploy
+        working-directory: ./deploy/terraform
         run: |
-          chmod +x deploy/scripts/terraform-apply.sh
+          echo "[*] Server deployment and configuration ..."
           export TF_TOKEN_app_terraform_io=$TERRAFORM_API_TOKEN
           export TF_VAR_api_key=$KAMATERA_API_KEY
           export TF_VAR_api_secret=$KAMATERA_API_SECRET
@@ -73,7 +74,10 @@ jobs:
           export TF_LOG=DEBUG
           export WORKSPACE=${{ inputs.workspace }}
           export ENVIRONMENT=${{ inputs.environment }}
-          ./deploy/scripts/run-terraform-apply.sh
+          echo "[*] Server deployment and configuration ... APPLY"
+          chmod +x deploy/scripts/terraform-apply.sh
+          ./deploy/scripts/terraform-apply.sh
+          echo "[+] Server deployment and configuration ... DONE"
 
       # Upload the Terraform output as an artifact
       - name: Upload Terraform Artifact
@@ -132,7 +136,7 @@ jobs:
       - name: Validate Terraform Output
         run: |
           if [ ! -f /tmp/tf_output.json ]; then
-            echo "Artifact terraform-output-${{ inputs.workspace }} not found or tf_output.json missing. Exiting."
+            echo "[!] Artifact terraform-output-${{ inputs.workspace }} not found or tf_output.json missing. Exiting."
             exit 1
           fi
 
@@ -169,14 +173,14 @@ jobs:
 
       # Set up GitHub Secrets
       - name: Get General Secrets
-        id: get-secrets
         uses: bitwarden/sm-action@v2
+        id: get-secrets
         with:
           access_token: ${{ secrets.BITWARDEN_TOKEN }}
           secrets: |
             f16fffe2-77b7-4d20-bf6c-b2c9015c71d3 > KAMATERA_PRIVATE_KEY
 
-      # Set up GitHub Secrets for Environment
+      # Set up SSH connection
       - name: Set up SSH connection
         env:
           KAMATERA_PRIVATE_KEY: ${{ steps.get-secrets.outputs.KAMATERA_PRIVATE_KEY }}
@@ -190,29 +194,21 @@ jobs:
         run: |
           scp -o StrictHostKeyChecking=no ~/.ssh/id_rsa root@${{ matrix.ip }}:/root/.ssh/id_rsa_temp || { echo "[x] Failed to transfer private key to remote server"; exit 1; }
 
-      # Step: Copy the initialization script securely to the remote server using scp
-      - name: Upload Initialization Scripts
+      # Initialize the server with initialization script
+      - name: Initialize BEFORE ${{ inputs.environment }} Server ${{ matrix.label }}
         run: |
-          # Copy the initialization scripts to the remote server
           echo "[*] Copying initialization script to remote server..."
           scp -o StrictHostKeyChecking=no "./deploy/scripts/initialize-begin.sh" root@${{ matrix.ip }}:/tmp/initialize-begin.sh || {
             echo "[x] Failed to transfer before initialization script to remote server"
             exit 1
           }
-          scp -o StrictHostKeyChecking=no "./deploy/scripts/initialize-end.sh" root@${{ matrix.ip }}:/tmp/initialize-end.sh || {
-            echo "[x] Failed to transfer after initialization script to remote server"
-            exit 1
-          }
-
-      # Initialize the server with initialization script
-      - name: Initialize BEFORE ${{ inputs.environment }} Server ${{ matrix.label }}
-        run: |
+          echo "[+] Copying initialization script to remote server...DONE"
           echo "[*] Executing BEFORE initializing remotely..."
           ssh -o StrictHostKeyChecking=no root@${{ matrix.ip }} << 'EOF'
             chmod +x /tmp/initialize-begin.sh
             /tmp/initialize-begin.sh
           EOF
-          echo "[*] Executing BEFORE initializing remotely...DONE"
+          echo "[+] Executing BEFORE initializing remotely...DONE"
 
       # Initialize the server with initialization script
       - name: Initialize ${{ inputs.environment }} Server ${{ matrix.label }}
@@ -223,12 +219,18 @@ jobs:
       # Initialize the server with initialization script
       - name: Initialize AFTER ${{ inputs.environment }} Server ${{ matrix.label }}
         run: |
+          echo "[*] Copying initialization script to remote server..."
+          scp -o StrictHostKeyChecking=no "./deploy/scripts/initialize-end.sh" root@${{ matrix.ip }}:/tmp/initialize-end.sh || {
+            echo "[x] Failed to transfer after initialization script to remote server"
+            exit 1
+          }
+          echo "[+] Copying initialization script to remote server...DONE"
           echo "[*] Executing AFTER initializing remotely..."
           ssh -o StrictHostKeyChecking=no root@${{ matrix.ip }} << 'EOF'
             chmod +x /tmp/initialize-end.sh
             /tmp/initialize-end.sh
           EOF
-          echo "[*] Executing AFTER initializing remotely...DONE"
+          echo "[+] Executing AFTER initializing remotely...DONE"
 
   # Configure the Swarm Cluster
   # This job will run if the cache is not hit or if the initialize input is set to true
@@ -261,8 +263,8 @@ jobs:
 
       # Set up GitHub Secrets
       - name: Get General Secrets
-        id: get-secrets
         uses: bitwarden/sm-action@v2
+        id: get-secrets
         with:
           access_token: ${{ secrets.BITWARDEN_TOKEN }}
           secrets: |
@@ -305,17 +307,22 @@ jobs:
           secrets: |
             6db5856c-3f7f-4b62-9846-b2c90144cb0b > APP_ROOT_PASSWORD
 
-      # Set up GitHub Secrets for Environment
+      # Set up SSH connection
       - name: Set up SSH connection
+        env:
+          KAMATERA_PRIVATE_KEY: ${{ steps.get-secrets.outputs.KAMATERA_PRIVATE_KEY }}
         run: |
-          chmod +x deploy/scripts/setup-ssh.sh
-          ./deploy/scripts/setup-ssh.sh "$KAMATERA_PRIVATE_KEY"
+          mkdir -p ~/.ssh
+          echo "$KAMATERA_PRIVATE_KEY" > ~/.ssh/id_rsa
+          chmod 600 ~/.ssh/id_rsa
 
       # Configure Swarm Server
       - name: Configure Server
         run: |
+          echo "[*] Server configuration..."
           chmod +x deploy/scripts/configure-swarm-server.sh
           ./deploy/scripts/configure-swarm-server.sh "${{ matrix.ip }}" "${{ inputs.environment }}"
+          echo "[+] Server configuration...DONE"
         env:
           PLATFORM_USERNAME: ${{ steps.get-secrets.outputs.PLATFORM_USERNAME }}
           PLATFORM_PASSWORD: ${{ steps.get-secrets.outputs.PLATFORM_PASSWORD }}
@@ -327,8 +334,10 @@ jobs:
       # Configure Application Services
       - name: Configure App Services
         run: |
-          chmod +x deploy/scripts/configure-app-services.sh
-          ./deploy/scripts/configure-app-services.sh "${{ matrix.ip }}"
+          echo "[*] Service configuration..."
+          chmod +x deploy/scripts/configure-services.sh
+          ./deploy/scripts/configure-services.sh "${{ matrix.ip }}"
+          echo "[+] Service configuration...DONE"
 
       # Finish Configuration
       - name: Finish Configuration
@@ -356,6 +365,7 @@ jobs:
       - name: Check Out
         uses: actions/checkout@v4
 
+      # Generate the service matrix to build
       - name: Generate Matrix
         id: set-matrix
         run: |
@@ -465,16 +475,20 @@ jobs:
       # Set up GitHub Secrets
       - name: Get General Secrets
         uses: bitwarden/sm-action@v2
+        id: get-secrets
         with:
           access_token: ${{ secrets.BITWARDEN_TOKEN }}
           secrets: |
             f16fffe2-77b7-4d20-bf6c-b2c9015c71d3 > KAMATERA_PRIVATE_KEY
 
-      # Set up GitHub Secrets for Environment
+      # Set up SSH connection
       - name: Set up SSH connection
+        env:
+          KAMATERA_PRIVATE_KEY: ${{ steps.get-secrets.outputs.KAMATERA_PRIVATE_KEY }}
         run: |
-          chmod +x deploy/scripts/setup-ssh.sh
-          ./deploy/scripts/setup-ssh.sh "$KAMATERA_PRIVATE_KEY"
+          mkdir -p ~/.ssh
+          echo "$KAMATERA_PRIVATE_KEY" > ~/.ssh/id_rsa
+          chmod 600 ~/.ssh/id_rsa
 
       # Start the environment
       - name: Start Environment
