Remove Traefik configuration files for develop and test environments; add Consul configuration and integration into deployment pipeline; update scripts for Consul setup; enhance Docker Compose with Consul service; modify environment files to include DATACENTER; add design analysis and configuration files for Consul and Traefik services.

diff --git a/.github/workflows/_pipeline.yml b/.github/workflows/_pipeline.yml
--- a/.github/workflows/_pipeline.yml
+++ b/.github/workflows/_pipeline.yml
@@ -556,6 +556,17 @@ jobs:
             exit 1
           }
           echo "[*] Deploying TRAEFIK to remote server...DONE"
+      
+      # Configure Consul Server
+      - name: Configure Consul
+        run: |
+          # CONSUL
+          echo "[*] Deploying CONSUL to remote server..."
+          scp -o StrictHostKeyChecking=no ./src/consul/* root@${{ matrix.ip }}:/app/consul/conf/ || {
+            echo "[x] Failed to transfer consul configuration to remote server"
+            exit 1
+          }
+          echo "[*] Deploying CONSUL to remote server...DONE"
 
       # Finish Configuration
       - name: Finish Configuration
