Add scripts for environment setup and teardown, including log clearing

diff --git a/.github/workflows/_task-configure.yml b/.github/workflows/_task-configure.yml
--- a/.github/workflows/_task-configure.yml
+++ b/.github/workflows/_task-configure.yml
@@ -53,64 +53,112 @@ jobs:
       - name: Check Out
         uses: actions/checkout@v4
 
-      # Configure the server for the app
+      # Load environment variables from .env file
+      - name: Get Environment Variables
+        run: |
+          set -a  # automatically export all variables
+          source ./src/${{ inputs.environment }}.env
+          set +a
+
+      # Set up GitHub Secrets
+      - name: Get Secrets
+        uses: bitwarden/sm-action@v2
+        with:  
+          access_token: ${{ secrets.BITWARDEN_TOKEN }}
+          secrets: |
+            f > VERSIO_USERNAME
+            f > VERSIO_PASSWORD
+
+      # Set up GitHub Secrets for Test Environment
+      - name: Get Test Secrets
+        if: ${{ inputs.environment == 'test' }}
+        uses: bitwarden/sm-action@v2
+        with:  
+          access_token: ${{ secrets.BITWARDEN_TOKEN }}
+          secrets: |
+            f16fffe2-77b7-4d20-bf6c-b2c9015c71d3 > KAMATERA_PRIVATE_KEY
+
+      # Set up GitHub Secrets for Staging Environment
+      - name: Get Staging Secrets
+        if: ${{ inputs.environment == 'staging' }}
+        uses: bitwarden/sm-action@v2
+        with:  
+          access_token: ${{ secrets.BITWARDEN_TOKEN }}
+          secrets: |
+            0c1f1f1c-456b-47d5-aad4-b2c9015ca6dc > KAMATERA_PRIVATE_KEY
+
+      # Set up GitHub Secrets for Production Environment
+      - name: Get Production Secrets
+        if: ${{ inputs.environment == 'production' }}
+        uses: bitwarden/sm-action@v2
+        with:  
+          access_token: ${{ secrets.BITWARDEN_TOKEN }}
+          secrets: |
+            02ed2dea7-b72e-401b-ae7e-b2c9015cd76e > KAMATERA_PRIVATE_KEY
+
+      # Set up SSH connection
+      - name: Set up SSH connection
+        run: |
+          mkdir -p ~/.ssh
+          echo "$KAMATERA_PRIVATE_KEY" > ~/.ssh/id_rsa
+          chmod 600 ~/.ssh/id_rsa
+
+      # Configure Swarm Server
       - name: Configure Server
         run: |
-          echo "Configuring IP: ${{ matrix.ip }}, Name: ${{ matrix.label }}"
-          ssh -o StrictHostKeyChecking=no root@${{ matrix.ip }} << 'EOF'
-            # Function to create a path if it does not already exist
-            function createpath() {
-              local newpath="$1"
-              if [ ! -d "$newpath" ]; then
-                  mkdir -p "$newpath"
-                  if [ $? -ne 0 ]; then
-                  echo "Error: Failed to create directory '$newpath'"
-                  return 1  # Return non-zero status to indicate failure
-                  fi
-                  #chmod 777 "$newpath"
-                  sudo chmod -R 777 "$newpath"
-              fi
-              return 0  # Return zero status to indicate success
-            }
-            
-            main() {
-              # Start of scripts
-              echo Updating server
-              echo Creating application directories
-              cd /
-              createpath "/app"
-
-              # Traefik
-              createpath "/app/traefik"
-              createpath "/app/traefik/conf"
-              createpath "/app/traefik/data"
-              createpath "/app/traefik/logs"
-            }
-
-            main
+          echo "[*] Generating configuration script..."
+          #envsubst < "./scripts/configure.template.sh" > "./scripts/configure.sh"
+          
+          echo "[*] Copying variables to remote server..."
+          cat <<EOF > /tmp/secrets.env
+          VERSIO_USERNAME=$version_username
+          VERSIO_PASSWORD=$version_password
           EOF
 
-      # Copy the generic files to the server
-      - name: Copy Generic Files
-        run: |
-          main() {
-            scp -o StrictHostKeyChecking=no /src/* root@${{ matrix.ip }}:/app/
+          # Copy secrets to remote server
+          scp -o StrictHostKeyChecking=no /tmp/secrets.env root@${{ matrix.ip }}:/tmp/secrets.env || {
+            echo "[x] Failed to transfer variables to remote server"
+            exit 1
           }
 
-          main
-
-      #
-      - name: Copy Traefik Files
-        run: |
-          main() {
-            scp -o StrictHostKeyChecking=no /src/traefik/* root@${{ matrix.ip }}:/app/traefik/conf
-
-            # Generate main.tf from template
-            cd /app/traefik/conf
-            echo "Generating config from template"
-            envsubst < traefik-config.template.yml > traefik-config.yml
-            rm -f traefik-config.template.yml
-            cat traefik-config.yml
+          # Copy environment variables to remote server
+          scp -o StrictHostKeyChecking=no ./src/${{ inputs.environment }}.env root@${{ matrix.ip }}:/tmp/variables.env || {
+            echo "[x] Failed to transfer variables to remote server"
+            exit 1
           }
 
-          main
+          # Copy the configuration script to the remote server
+          echo "[*] Copying configuration script to remote server..."
+          scp -o StrictHostKeyChecking=no "./scripts/configure.sh" root@${{ matrix.ip }}:/tmp/configure.sh || {
+            echo "[x] Failed to transfer configuration script to remote server"
+            exit 1
+          }
+
+          # Copy the SSH key to the remote server
+          echo "[*] Executing configuration script remotely..."
+          ssh -o StrictHostKeyChecking=no root@${{ matrix.ip }} << 'EOF'
+            chmod +x /tmp/configure.sh
+            /tmp/configure.sh
+          EOF
+
+          # Copy /src to /app
+          echo "[*] Copying source to remote server..."
+          find ./src -maxdepth 1 -type f -exec scp -o StrictHostKeyChecking=no {} root@${{ matrix.ip }}:/app/ \;
+
+          # TRAEFIK
+          echo "[*] Deploying TRAEFIK to remote server..."
+          envsubst '${DOMAIN} ${EMAIL}' < "./src/traefik/traefik-conf.template.yml" > "./src/traefik/traefik-conf.yml"
+          rm -f "./src/traefik/traefik-conf.template.yml"
+          scp -o StrictHostKeyChecking=no "./src/traefik/*" root@${{ matrix.ip }}:/app/traefik/conf/* || {
+            echo "[x] Failed to transfer traefik configuration to remote server"
+            exit 1
+          }
+          echo "[*] Deploying TRAEFIK to remote server...DONE"
+
+          # Cleanup
+          echo "[*] Cleanup temporary files..."
+          ssh -o StrictHostKeyChecking=no root@${{ matrix.ip }} << 'EOF'
+            rm -f /tmp/variables.env
+            rm -f /tmp/secrets.env
+          EOF
+          echo "[*] Cleanup temporary files...DONE"
